---

  - name: Disable docker service
    service: name=docker enabled=yes state=stopped

  - name: Purge Docker for Increasing devicemapper
    command: bash -c "rm -rf /var/lib/docker"

  - name: Create new devicemapper directory
    command: bash -c "mkdir -p /var/lib/docker/devicemapper/devicemapper"

  - name: Allocate devicemapper sparse file space
    command: bash -c "dd if=/dev/zero of=/var/lib/docker/devicemapper/devicemapper/data bs=1G count=0 seek={{ docker_devicemapper_size }}"
