---
#Install Docker Latest

 - name: Install utilities
   yum: name={{ item }}  state=latest
   with_items:
    - curl
   register: utilities

 - debug: msg="{{ utilities.results }}"

 - name: Install latest docker
   command: bash -c "curl -sSL https://get.docker.com/ | sh"
   register: dockerinstall

 - debug: msg="{{ dockerinstall }}"
